// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjqswgmejlitaqyvtxdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqcXN3Z21lamxpdGFxeXZ0eGRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzI5MjMsImV4cCI6MjA2MDQwODkyM30.U36LCnz3wWTJ5XkJdTHMREsnA7gMlxlFOxV6SI7ANOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);